#!/bin/bash

# put device name here to run fio test for 
# multiple disks in parallel
# example disks=(sfdv0n1 sfdv1n1 nvme0n1 nvme1n1)
disks=(md0)
# example expansion_ratio=(3200 6400 9600)
expansion_ratio=()
# change the numbers below to control compressibility
# generated by fio. larger number means higher 
# compressibility
# example comp_ratio=(60 75 90)
comp_ratio=(60 75)
comp_opt_str="";
# example block_size=(4 16 32 64)
block_size=(4 16 512 1024 4096 8192)

fio_test(){
for comp_num in ${comp_ratio[@]};
do
for bss in ${block_size[@]};
do
if [ "${comp_num}" != "" ];
then
    comp_opt_str=" --buffer_compress_chunk=4k --buffer_compress_percentage=${comp_num} "
fi

timestamp=`echo $0`_${comp_num}_${bss}k_`date +%Y%m%d_%H%M`

if [ ! -d "${timestamp}" ]; then mkdir ${timestamp}; fi

for disk in ${disks[@]};
do
    if echo "${disk}" |grep nvme > /dev/null;then
        echo y | nvme format "/dev/""$disk"
        nvme smart-log /dev/${disk} > ${timestamp}/${disk}_smart-log_start.txt
        nvme intel smart-log-add /dev/${disk} > ${timestamp}/${disk}_smart-log-add_start.txt
    elif echo "${disk}" |grep md0 > /dev/null;then
       mdadm --stop /dev/md0
       echo y | sfx-nvme format /dev/sfdv0n1
       echo y | sfx-nvme format /dev/sfdv1n1
       echo;echo y | mdadm --create /dev/md0 --level=mirror --raid-devices=2 /dev/sfdv0n1 /dev/sfdv1n1
       mdadm -E /dev/sfdv0n1 /dev/sfdv1n1
       mdadm --detail /dev/md0 > ${timestamp}/${disk}_start.txt 
       sfx-nvme smart-log /dev/sfdv0n1 > ${timestamp}/sfdv0n1_smart-log_start.txt
       sfx-nvme sfx smart-log-add /dev/sfdv0n1 > ${timestamp}/sfdv0n1_smart-log-add_start.txt
       sfx-status  /dev/sfdv0n1  > ${timestamp}/sfdv0n1_sfx-status_start.txt
       sfx-nvme smart-log /dev/sfdv1n1 > ${timestamp}/sfdv1n1_smart-log_start.txt
       sfx-nvme sfx smart-log-add /dev/sfdv1n1 > ${timestamp}/sfdv1n1_smart-log-add_start.txt
       sfx-status  /dev/sfdv1n1  > ${timestamp}/sfdv1n1_sfx-status_start.txt
    fi
done

pid_list=""
for disk in ${disks[@]};
do
    #echo y | sfx-nvme format "/dev/""$disk"
    iostat -dxmct 1 ${disk} > ${timestamp}/${disk}.iostat &
    sed -i "s/[0-9]\{1,\}[k|K]/${bss}k/g" baseline.fio
    fio ${comp_opt_str} \
        --filename=/dev/${disk} \
        --output=${timestamp}/${disk}.fio \
        ./baseline.fio &
    pid_list="${pid_list} $!"
done

wait ${pid_list}
pkill -9 iostat
for disk in ${disks[@]};
do
    if echo "${disk}" |grep nvme > /dev/null;then
        nvme smart-log /dev/${disk} > ${timestamp}/${disk}_smart-log_end.txt
        nvme intel smart-log-add /dev/${disk} > ${timestamp}/${disk}_smart-log-add_end.txt
    elif echo "${disk}" |grep md0 > /dev/null;then
       mdadm --detail /dev/md0 > ${timestamp}/${disk}_end.txt
       sfx-nvme smart-log /dev/sfdv0n1 > ${timestamp}/sfdv0n1_smart-log_end.txt
       sfx-nvme sfx smart-log-add /dev/sfdv0n1 > ${timestamp}/sfdv0n1_smart-log-add_end.txt
       sfx-status  /dev/sfdv0n1  > ${timestamp}/sfdv0n1_sfx-status_end.txt
       sfx-nvme smart-log /dev/sfdv1n1 > ${timestamp}/sfdv1n1_smart-log_end.txt
       sfx-nvme sfx smart-log-add /dev/sfdv1n1 > ${timestamp}/sfdv1n1_smart-log-add_end.txt
       sfx-status  /dev/sfdv1n1  > ${timestamp}/sfdv1n1_sfx-status_end.txt
    fi
done

pushd ${timestamp}
iofields="1,4-9,14"
cpufields="1-2,4"
for fiostat in `ls *.iostat`
do
    grep -m1 Device $fiostat | sed -r "s/\s+/,/g" | cut -d, -f ${iofields} > ${fiostat}_io.csv
    grep -e sfd -e nvme -e md $fiostat | sed -r "s/\s+/,/g"  | cut -d, -f ${iofields} >> ${fiostat}_io.csv

    grep -m1 avg-cpu $fiostat | sed -r "s/\s+/,/g" | cut -d, -f ${cpufields} > ${fiostat}_cpu.csv
    grep -A1 avg-cpu $fiostat | grep -v \- | sed -r "s/\s+/,/g" | cut -d, -f ${cpufields} >> ${fiostat}_cpu.csv
    
    paste -d, ${fiostat}_io.csv ${fiostat}_cpu.csv > ${fiostat}.csv
    rm ${fiostat}_io.csv ${fiostat}_cpu.csv
done
popd
done
done
}

if [ ${#expansion_ratio[@]} -ne 0 ];then
  for expansions in ${expansion_ratio[@]};
  do
    for disk in ${disks[@]};
    do
      if echo "${disk}" | grep sfd > /dev/null;then
        echo y | sfx-nvme sfx change-cap /dev/${disk} -c ${expansions}
        sleep 1
      fi
    done
    fio_test
  done
else
  fio_test
fi
